// Code generated by qtc from "basepage.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// This is a base page template. All the other template pages implement this interface.
//

//line views/basepage.qtpl:3
package views

//line views/basepage.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/basepage.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/basepage.qtpl:4
type Page interface {
//line views/basepage.qtpl:4
	Title() string
//line views/basepage.qtpl:4
	StreamTitle(qw422016 *qt422016.Writer)
//line views/basepage.qtpl:4
	WriteTitle(qq422016 qtio422016.Writer)
//line views/basepage.qtpl:4
	Head() string
//line views/basepage.qtpl:4
	StreamHead(qw422016 *qt422016.Writer)
//line views/basepage.qtpl:4
	WriteHead(qq422016 qtio422016.Writer)
//line views/basepage.qtpl:4
	Body() string
//line views/basepage.qtpl:4
	StreamBody(qw422016 *qt422016.Writer)
//line views/basepage.qtpl:4
	WriteBody(qq422016 qtio422016.Writer)
//line views/basepage.qtpl:4
	Scripts() string
//line views/basepage.qtpl:4
	StreamScripts(qw422016 *qt422016.Writer)
//line views/basepage.qtpl:4
	WriteScripts(qq422016 qtio422016.Writer)
//line views/basepage.qtpl:4
}

// Page prints a page implementing Page interface.

//line views/basepage.qtpl:14
func StreamPageTemplate(qw422016 *qt422016.Writer, p Page) {
//line views/basepage.qtpl:14
	qw422016.N().S(`
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
<meta name="description" content="Dreamvat Hub Host" />
<meta name="author" content="Lukiya Chen" />
<title>`)
//line views/basepage.qtpl:22
	p.StreamTitle(qw422016)
//line views/basepage.qtpl:22
	qw422016.N().S(`</title>
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" rel="stylesheet" />
<link href="/css/site.min.css" rel="stylesheet">
`)
//line views/basepage.qtpl:26
	p.StreamHead(qw422016)
//line views/basepage.qtpl:26
	qw422016.N().S(`
</head>
<body class="text-center">
`)
//line views/basepage.qtpl:29
	p.StreamBody(qw422016)
//line views/basepage.qtpl:29
	qw422016.N().S(`
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
`)
//line views/basepage.qtpl:32
	p.StreamScripts(qw422016)
//line views/basepage.qtpl:32
	qw422016.N().S(`
</body>
</html>
`)
//line views/basepage.qtpl:35
}

//line views/basepage.qtpl:35
func WritePageTemplate(qq422016 qtio422016.Writer, p Page) {
//line views/basepage.qtpl:35
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/basepage.qtpl:35
	StreamPageTemplate(qw422016, p)
//line views/basepage.qtpl:35
	qt422016.ReleaseWriter(qw422016)
//line views/basepage.qtpl:35
}

//line views/basepage.qtpl:35
func PageTemplate(p Page) string {
//line views/basepage.qtpl:35
	qb422016 := qt422016.AcquireByteBuffer()
//line views/basepage.qtpl:35
	WritePageTemplate(qb422016, p)
//line views/basepage.qtpl:35
	qs422016 := string(qb422016.B)
//line views/basepage.qtpl:35
	qt422016.ReleaseByteBuffer(qb422016)
//line views/basepage.qtpl:35
	return qs422016
//line views/basepage.qtpl:35
}

// Base page implementation. Other pages may inherit from it if they need
// overriding only certain Page methods

//line views/basepage.qtpl:40
type BasePage struct{}

//line views/basepage.qtpl:41
func (p *BasePage) StreamTitle(qw422016 *qt422016.Writer) {
//line views/basepage.qtpl:41
	qw422016.N().S(`Test Auth Server`)
//line views/basepage.qtpl:41
}

//line views/basepage.qtpl:41
func (p *BasePage) WriteTitle(qq422016 qtio422016.Writer) {
//line views/basepage.qtpl:41
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/basepage.qtpl:41
	p.StreamTitle(qw422016)
//line views/basepage.qtpl:41
	qt422016.ReleaseWriter(qw422016)
//line views/basepage.qtpl:41
}

//line views/basepage.qtpl:41
func (p *BasePage) Title() string {
//line views/basepage.qtpl:41
	qb422016 := qt422016.AcquireByteBuffer()
//line views/basepage.qtpl:41
	p.WriteTitle(qb422016)
//line views/basepage.qtpl:41
	qs422016 := string(qb422016.B)
//line views/basepage.qtpl:41
	qt422016.ReleaseByteBuffer(qb422016)
//line views/basepage.qtpl:41
	return qs422016
//line views/basepage.qtpl:41
}

//line views/basepage.qtpl:42
func (p *BasePage) StreamBody(qw422016 *qt422016.Writer) {
//line views/basepage.qtpl:42
}

//line views/basepage.qtpl:42
func (p *BasePage) WriteBody(qq422016 qtio422016.Writer) {
//line views/basepage.qtpl:42
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/basepage.qtpl:42
	p.StreamBody(qw422016)
//line views/basepage.qtpl:42
	qt422016.ReleaseWriter(qw422016)
//line views/basepage.qtpl:42
}

//line views/basepage.qtpl:42
func (p *BasePage) Body() string {
//line views/basepage.qtpl:42
	qb422016 := qt422016.AcquireByteBuffer()
//line views/basepage.qtpl:42
	p.WriteBody(qb422016)
//line views/basepage.qtpl:42
	qs422016 := string(qb422016.B)
//line views/basepage.qtpl:42
	qt422016.ReleaseByteBuffer(qb422016)
//line views/basepage.qtpl:42
	return qs422016
//line views/basepage.qtpl:42
}

//line views/basepage.qtpl:43
func (p *BasePage) StreamHead(qw422016 *qt422016.Writer) {
//line views/basepage.qtpl:43
}

//line views/basepage.qtpl:43
func (p *BasePage) WriteHead(qq422016 qtio422016.Writer) {
//line views/basepage.qtpl:43
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/basepage.qtpl:43
	p.StreamHead(qw422016)
//line views/basepage.qtpl:43
	qt422016.ReleaseWriter(qw422016)
//line views/basepage.qtpl:43
}

//line views/basepage.qtpl:43
func (p *BasePage) Head() string {
//line views/basepage.qtpl:43
	qb422016 := qt422016.AcquireByteBuffer()
//line views/basepage.qtpl:43
	p.WriteHead(qb422016)
//line views/basepage.qtpl:43
	qs422016 := string(qb422016.B)
//line views/basepage.qtpl:43
	qt422016.ReleaseByteBuffer(qb422016)
//line views/basepage.qtpl:43
	return qs422016
//line views/basepage.qtpl:43
}

//line views/basepage.qtpl:44
func (p *BasePage) StreamScripts(qw422016 *qt422016.Writer) {
//line views/basepage.qtpl:44
}

//line views/basepage.qtpl:44
func (p *BasePage) WriteScripts(qq422016 qtio422016.Writer) {
//line views/basepage.qtpl:44
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/basepage.qtpl:44
	p.StreamScripts(qw422016)
//line views/basepage.qtpl:44
	qt422016.ReleaseWriter(qw422016)
//line views/basepage.qtpl:44
}

//line views/basepage.qtpl:44
func (p *BasePage) Scripts() string {
//line views/basepage.qtpl:44
	qb422016 := qt422016.AcquireByteBuffer()
//line views/basepage.qtpl:44
	p.WriteScripts(qb422016)
//line views/basepage.qtpl:44
	qs422016 := string(qb422016.B)
//line views/basepage.qtpl:44
	qt422016.ReleaseByteBuffer(qb422016)
//line views/basepage.qtpl:44
	return qs422016
//line views/basepage.qtpl:44
}
