// Code generated by qtc from "index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Main page template. Implements BasePage methods.
//

//line views/index.qtpl:3
package views

//line views/index.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/index.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/index.qtpl:4
type IndexPage struct {
	BasePage
}

//line views/index.qtpl:10
func (p *IndexPage) StreamBody(qw422016 *qt422016.Writer) {
//line views/index.qtpl:10
	qw422016.N().S(`
<h1>Welcome</h1>
`)
//line views/index.qtpl:12
}

//line views/index.qtpl:12
func (p *IndexPage) WriteBody(qq422016 qtio422016.Writer) {
//line views/index.qtpl:12
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/index.qtpl:12
	p.StreamBody(qw422016)
//line views/index.qtpl:12
	qt422016.ReleaseWriter(qw422016)
//line views/index.qtpl:12
}

//line views/index.qtpl:12
func (p *IndexPage) Body() string {
//line views/index.qtpl:12
	qb422016 := qt422016.AcquireByteBuffer()
//line views/index.qtpl:12
	p.WriteBody(qb422016)
//line views/index.qtpl:12
	qs422016 := string(qb422016.B)
//line views/index.qtpl:12
	qt422016.ReleaseByteBuffer(qb422016)
//line views/index.qtpl:12
	return qs422016
//line views/index.qtpl:12
}
