// Code generated by qtc from "login.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Main page template. Implements BasePage methods.
//

//line views/login.qtpl:3
package views

//line views/login.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/login.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/login.qtpl:4
type LoginPage struct {
	BasePage
	ReturnURL string
}

//line views/login.qtpl:11
func (p *LoginPage) StreamBody(qw422016 *qt422016.Writer) {
//line views/login.qtpl:11
	qw422016.N().S(`
<div class="login-form">
<form class="form-signin" action="/account/login?returnUrl=`)
//line views/login.qtpl:13
	qw422016.E().S(p.ReturnURL)
//line views/login.qtpl:13
	qw422016.N().S(`" method="post">
<div class="avatar"><i class="far fa-user"></i></div>
<h4 class="modal-title">Login to Your Account</h4>
<div class="form-group">
<input type="text" name="Username" class="form-control" placeholder="Username" required autofocus />
</div>
<div class="form-group">
<input type="password" name="Password" class="form-control" placeholder="Password" required />
</div>
<div class="form-group small clearfix">
<label class="checkbox-inline"><input type="checkbox" /> Remember me</label>
<a href="#" class="forgot-link">Forgot Password?</a>
</div>
<button type="submit" class="btn btn-primary btn-block btn-lg" value="Login">Login</button>
<input id="Token" name="Token" type="hidden" />
</form>
</div>
`)
//line views/login.qtpl:30
}

//line views/login.qtpl:30
func (p *LoginPage) WriteBody(qq422016 qtio422016.Writer) {
//line views/login.qtpl:30
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/login.qtpl:30
	p.StreamBody(qw422016)
//line views/login.qtpl:30
	qt422016.ReleaseWriter(qw422016)
//line views/login.qtpl:30
}

//line views/login.qtpl:30
func (p *LoginPage) Body() string {
//line views/login.qtpl:30
	qb422016 := qt422016.AcquireByteBuffer()
//line views/login.qtpl:30
	p.WriteBody(qb422016)
//line views/login.qtpl:30
	qs422016 := string(qb422016.B)
//line views/login.qtpl:30
	qt422016.ReleaseByteBuffer(qb422016)
//line views/login.qtpl:30
	return qs422016
//line views/login.qtpl:30
}

//line views/login.qtpl:32
func (p *LoginPage) StreamScripts(qw422016 *qt422016.Writer) {
//line views/login.qtpl:32
	qw422016.N().S(`
<script src="https://www.google.com/recaptcha/api.js?render=xxxx"></script>
`)
//line views/login.qtpl:34
}

//line views/login.qtpl:34
func (p *LoginPage) WriteScripts(qq422016 qtio422016.Writer) {
//line views/login.qtpl:34
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/login.qtpl:34
	p.StreamScripts(qw422016)
//line views/login.qtpl:34
	qt422016.ReleaseWriter(qw422016)
//line views/login.qtpl:34
}

//line views/login.qtpl:34
func (p *LoginPage) Scripts() string {
//line views/login.qtpl:34
	qb422016 := qt422016.AcquireByteBuffer()
//line views/login.qtpl:34
	p.WriteScripts(qb422016)
//line views/login.qtpl:34
	qs422016 := string(qb422016.B)
//line views/login.qtpl:34
	qt422016.ReleaseByteBuffer(qb422016)
//line views/login.qtpl:34
	return qs422016
//line views/login.qtpl:34
}
